### ISSUE TITLE
Why this is transferred with MIME type text/html?

### ISSUE THREAD

**Issue by miliu99** [mgcrea/bootstrap-additions#13]
I installed bootstrap-additions using bower to my WebStorm project. And I got this error/warning in my chrome: Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:3000/lib/bootstrap-additions/bootstrap-additions.min.css". Why? Is this a WebStorm problem (but I don't have problem with other stylesheets)?

**Comment by mgcrea** [comment]
You should try with the latest release. Probably a netstorm issue though.
