### ISSUE TITLE
Include individually-built component files in dist directory

### ISSUE THREAD

**Issue by joshuajabbour** [mgcrea/bootstrap-additions#15]
I'd love to be able to include only specific additions. If this package built out each component into the dist directory (maybe under `dist/components/datepicker.css`, etc), that would be possible.

The main `bootstrap-additions.css` should still be the default, but for users who need more flexibility, component distributions would be great.

**Comment by mgcrea** [comment]
done with the `v0.3.0` release. Thanks for the feedback.
