### ISSUE TITLE
can this be used without angular-strap

### ISSUE THREAD

**Issue by dcsan** [mgcrea/bootstrap-additions#4]
I wanted to use the aside in a meteor.js project, so just plucked the css out

and the example from angularstrap, however things aren't that simple it seems.
is the javascript to make this work part of the angular strap repo?

```
<button type="button" class="btn btn-lg btn-primary" bs-aside="aside">Click to toggle aside
  <br>
  <small>(using an object)</small>
</button>
```

**Comment by mgcrea** [comment]
Yep it is. All the JS is @angular-strap.
